#:schema node_modules/wrangler/config-schema.json

compatibility_date = "2025-11-17"
main = "src/index.ts"
name = "noris-decap-oauth"

# Use workers.dev until norislaw.com is added as a Cloudflare DNS zone.
workers_dev = true

[vars]
GITHUB_REPO_PRIVATE = "1"
